# Generated by Django 2.1.5 on 2021-02-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=50, null=True)),
                ('url', models.URLField()),
                ('method', models.IntegerField(choices=[(0, 'GET'), (1, 'POST')], default=0)),
                ('body_type', models.IntegerField(choices=[(0, 'None'), (1, 'URL-ENCODE'), (2, 'JSON')], default=0)),
                ('header', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('update_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='title', max_length=20, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('owner', models.CharField(db_column='base_url', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
