# Generated by Django 2.1.5 on 2021-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='update_time',
            field=models.DateField(),
        ),
    ]
