# Generated by Django 2.1.5 on 2021-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
