# Generated by Django 2.1.5 on 2021-03-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('header', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('update_time', models.DateTimeField()),
                ('depends', models.TextField(null=True)),
                ('depens_infos', models.TextField(null=True)),
                ('checks', models.TimeField(null=True)),
                ('check_code', models.IntegerField(default=200)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiInfo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
    ]
