# Generated by Django 2.1.5 on 2021-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_caseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='checks',
            field=models.TextField(null=True),
        ),
    ]
